// Code generated by hertz generator.

package main

import (
	handler "github.com/CloudStriver/cloudmind-core-api/biz/adaptor/controller"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
