// Code generated by hertz generator.

package core_api

import (
	"context"

	core_api "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/cloudmind/core_api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateComment .
// @router /comment/createComment [POST]
func CreateComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.CreateCommentResp)

	c.JSON(consts.StatusOK, resp)
}

// GetComment .
// @router /comment/getComment [GET]
func GetComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetCommentResp)

	c.JSON(consts.StatusOK, resp)
}

// GetComments .
// @router /comment/getComments [GET]
func GetComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetCommentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetCommentsResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteComment .
// @router /comment/deleteComment [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.DeleteCommentResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateComment .
// @router /comment/updateComment [POST]
func UpdateComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.UpdateCommentResp)

	c.JSON(consts.StatusOK, resp)
}

// SetCommentAttrs .
// @router /comment/setCommentAttrs [POST]
func SetCommentAttrs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SetCommentAttrsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.SetCommentAttrsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetCommentSubject .
// @router /comment/getCommentSubject [GET]
func GetCommentSubject(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetCommentSubjectReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetCommentSubjectResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateCommentSubject .
// @router /comment/updateCommentSubject [POST]
func UpdateCommentSubject(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateCommentSubjectReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.UpdateCommentSubjectResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteCommentSubject .
// @router /comment/deleteCommentSubject [POST]
func DeleteCommentSubject(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteCommentSubjectReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.DeleteCommentSubjectResp)

	c.JSON(consts.StatusOK, resp)
}

// CreateRelation .
// @router /relation/createRelation [POST]
func CreateRelation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateRelationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.CreateRelationResp)

	c.JSON(consts.StatusOK, resp)
}

// GetFromRelations .
// @router /relation/getFromRelations [GET]
func GetFromRelations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetFromRelationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetFromRelationsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetToRelations .
// @router /relation/getToRelations [GET]
func GetToRelations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetToRelationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetToRelationsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetRelation .
// @router /relation/getRelation [GET]
func GetRelation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetRelationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetRelationResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteRelation .
// @router /relation/deleteRelation [POST]
func DeleteRelation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteRelationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.DeleteRelationResp)

	c.JSON(consts.StatusOK, resp)
}

// GetRelationPaths .
// @router /relation/getRelationPaths [GET]
func GetRelationPaths(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetRelationPathsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetRelationPathsResp)

	c.JSON(consts.StatusOK, resp)
}
