// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/CloudStriver/cloudmind-core-api/biz/adaptor"
	"github.com/CloudStriver/cloudmind-core-api/provider"

	core_api "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/cloudmind/core_api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ApplySignedUrl .
// @router /sts [POST]
func ApplySignedUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ApplySignedUrlReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ApplySignedUrlResp)
	p := provider.Get()
	resp, err = p.StsService.ApplySignedUrl(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
