// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/CloudStriver/cloudmind-core-api/biz/adaptor"
	"github.com/CloudStriver/cloudmind-core-api/provider"

	core_api "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/cloudmind/core_api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetNotifications .
// @router /system/getNotifications [GET]
func GetNotifications(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetNotificationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetNotificationsResp)
	p := provider.Get()
	resp, err = p.NotificationService.GetNotifications(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetNotificationCount .
// @router /system/getNotificationCount [GET]
func GetNotificationCount(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetNotificationCountReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetNotificationCountResp)
	p := provider.Get()
	resp, err = p.NotificationService.GetNotificationCount(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// UpdateNotifications .
// @router /system/updateNotifications [POST]
func UpdateNotifications(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateNotificationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.UpdateNotificationsResp)
	p := provider.Get()
	resp, err = p.NotificationService.UpdateNotifications(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
