// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	core_api "github.com/CloudStriver/cloudmind-core-api/biz/adaptor/router/core_api"
	"github.com/cloudwego/hertz/pkg/app/server"
)
 
// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	core_api.Register(r)
}
