// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: cloudmind/core_api/auth.proto

package core_api

import (
	_ "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/basic"
	_ "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/cloudmind/content"
	_ "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/cloudmind/sts"
	_ "github.com/CloudStriver/cloudmind-core-api/biz/application/dto/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadType int32

const (
	UploadType_UnknownUploadType       UploadType = 0
	UploadType_UserAvatarUploadType    UploadType = 1
	UploadType_PostAvatarUploadType    UploadType = 2
	UploadType_ProductAvatarUploadType UploadType = 3
)

// Enum value maps for UploadType.
var (
	UploadType_name = map[int32]string{
		0: "UnknownUploadType",
		1: "UserAvatarUploadType",
		2: "PostAvatarUploadType",
		3: "ProductAvatarUploadType",
	}
	UploadType_value = map[string]int32{
		"UnknownUploadType":       0,
		"UserAvatarUploadType":    1,
		"PostAvatarUploadType":    2,
		"ProductAvatarUploadType": 3,
	}
)

func (x UploadType) Enum() *UploadType {
	p := new(UploadType)
	*p = x
	return p
}

func (x UploadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloudmind_core_api_auth_proto_enumTypes[0].Descriptor()
}

func (UploadType) Type() protoreflect.EnumType {
	return &file_cloudmind_core_api_auth_proto_enumTypes[0]
}

func (x UploadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadType.Descriptor instead.
func (UploadType) EnumDescriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{0}
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name" query:"name" vd:"len($) >= 1 && len($) <= 20"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email" form:"email" query:"email" vd:"email($)"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" form:"password" query:"password"`
	IsSure   bool   `protobuf:"varint,4,opt,name=isSure,proto3" json:"isSure" form:"isSure" query:"isSure"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetIsSure() bool {
	if x != nil {
		return x.IsSure
	}
	return false
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string      `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string      `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string      `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
	Keywords   []*Keywords `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords" form:"keywords" query:"keywords"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *RegisterResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *RegisterResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResp) GetKeywords() []*Keywords {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type EmailLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" form:"email" query:"email" vd:"email($)"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" form:"password" query:"password"`
}

func (x *EmailLoginReq) Reset() {
	*x = EmailLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginReq) ProtoMessage() {}

func (x *EmailLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginReq.ProtoReflect.Descriptor instead.
func (*EmailLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *EmailLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmailLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
}

func (x *EmailLoginResp) Reset() {
	*x = EmailLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginResp) ProtoMessage() {}

func (x *EmailLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginResp.ProtoReflect.Descriptor instead.
func (*EmailLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *EmailLoginResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *EmailLoginResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *EmailLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GithubLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
}

func (x *GithubLoginReq) Reset() {
	*x = GithubLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubLoginReq) ProtoMessage() {}

func (x *GithubLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubLoginReq.ProtoReflect.Descriptor instead.
func (*GithubLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GithubLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GithubLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
}

func (x *GithubLoginResp) Reset() {
	*x = GithubLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubLoginResp) ProtoMessage() {}

func (x *GithubLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubLoginResp.ProtoReflect.Descriptor instead.
func (*GithubLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GithubLoginResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *GithubLoginResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *GithubLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GiteeLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
}

func (x *GiteeLoginReq) Reset() {
	*x = GiteeLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiteeLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiteeLoginReq) ProtoMessage() {}

func (x *GiteeLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiteeLoginReq.ProtoReflect.Descriptor instead.
func (*GiteeLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GiteeLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GiteeLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
}

func (x *GiteeLoginResp) Reset() {
	*x = GiteeLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiteeLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiteeLoginResp) ProtoMessage() {}

func (x *GiteeLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiteeLoginResp.ProtoReflect.Descriptor instead.
func (*GiteeLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GiteeLoginResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *GiteeLoginResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *GiteeLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WxMaUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId    string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId" form:"openId" query:"openId"`
	NickName  string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName" form:"nickName" query:"nickName"`
	Gender    int64  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender" form:"gender" query:"gender"`
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatarUrl,proto3" json:"avatarUrl" form:"avatarUrl" query:"avatarUrl"`
}

func (x *WxMaUserInfo) Reset() {
	*x = WxMaUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxMaUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxMaUserInfo) ProtoMessage() {}

func (x *WxMaUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxMaUserInfo.ProtoReflect.Descriptor instead.
func (*WxMaUserInfo) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{8}
}

func (x *WxMaUserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *WxMaUserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *WxMaUserInfo) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *WxMaUserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type WeixinCallBackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanSuccess  bool          `protobuf:"varint,1,opt,name=scanSuccess,proto3" json:"scanSuccess" form:"scanSuccess" query:"scanSuccess"`
	CancelLogin  bool          `protobuf:"varint,2,opt,name=cancelLogin,proto3" json:"cancelLogin" form:"cancelLogin" query:"cancelLogin"`
	TempUserId   string        `protobuf:"bytes,3,opt,name=tempUserId,proto3" json:"tempUserId" form:"tempUserId" query:"tempUserId"`
	WxMaUserInfo *WxMaUserInfo `protobuf:"bytes,4,opt,name=wxMaUserInfo,proto3" json:"wxMaUserInfo" form:"wxMaUserInfo" query:"wxMaUserInfo"`
}

func (x *WeixinCallBackReq) Reset() {
	*x = WeixinCallBackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinCallBackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinCallBackReq) ProtoMessage() {}

func (x *WeixinCallBackReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinCallBackReq.ProtoReflect.Descriptor instead.
func (*WeixinCallBackReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{9}
}

func (x *WeixinCallBackReq) GetScanSuccess() bool {
	if x != nil {
		return x.ScanSuccess
	}
	return false
}

func (x *WeixinCallBackReq) GetCancelLogin() bool {
	if x != nil {
		return x.CancelLogin
	}
	return false
}

func (x *WeixinCallBackReq) GetTempUserId() string {
	if x != nil {
		return x.TempUserId
	}
	return ""
}

func (x *WeixinCallBackReq) GetWxMaUserInfo() *WxMaUserInfo {
	if x != nil {
		return x.WxMaUserInfo
	}
	return nil
}

type WeixinCallBackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg" query:"msg"`
}

func (x *WeixinCallBackResp) Reset() {
	*x = WeixinCallBackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinCallBackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinCallBackResp) ProtoMessage() {}

func (x *WeixinCallBackResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinCallBackResp.ProtoReflect.Descriptor instead.
func (*WeixinCallBackResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{10}
}

func (x *WeixinCallBackResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WeixinCallBackResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WeixinLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WeixinLoginReq) Reset() {
	*x = WeixinLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinLoginReq) ProtoMessage() {}

func (x *WeixinLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinLoginReq.ProtoReflect.Descriptor instead.
func (*WeixinLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{11}
}

type WeixinLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrUrl      string `protobuf:"bytes,1,opt,name=qrUrl,proto3" json:"qrUrl" form:"qrUrl" query:"qrUrl"`
	TempUserId string `protobuf:"bytes,2,opt,name=tempUserId,proto3" json:"tempUserId" form:"tempUserId" query:"tempUserId"`
}

func (x *WeixinLoginResp) Reset() {
	*x = WeixinLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinLoginResp) ProtoMessage() {}

func (x *WeixinLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinLoginResp.ProtoReflect.Descriptor instead.
func (*WeixinLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{12}
}

func (x *WeixinLoginResp) GetQrUrl() string {
	if x != nil {
		return x.QrUrl
	}
	return ""
}

func (x *WeixinLoginResp) GetTempUserId() string {
	if x != nil {
		return x.TempUserId
	}
	return ""
}

type WeixinIsLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempUserId string `protobuf:"bytes,1,opt,name=tempUserId,proto3" json:"tempUserId" form:"tempUserId" query:"tempUserId"`
}

func (x *WeixinIsLoginReq) Reset() {
	*x = WeixinIsLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinIsLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinIsLoginReq) ProtoMessage() {}

func (x *WeixinIsLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinIsLoginReq.ProtoReflect.Descriptor instead.
func (*WeixinIsLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{13}
}

func (x *WeixinIsLoginReq) GetTempUserId() string {
	if x != nil {
		return x.TempUserId
	}
	return ""
}

type WeixinIsLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status" form:"status" query:"status"`
}

func (x *WeixinIsLoginResp) Reset() {
	*x = WeixinIsLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeixinIsLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinIsLoginResp) ProtoMessage() {}

func (x *WeixinIsLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinIsLoginResp.ProtoReflect.Descriptor instead.
func (*WeixinIsLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{14}
}

func (x *WeixinIsLoginResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *WeixinIsLoginResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *WeixinIsLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WeixinIsLoginResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QQLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
}

func (x *QQLoginReq) Reset() {
	*x = QQLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QQLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQLoginReq) ProtoMessage() {}

func (x *QQLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQLoginReq.ProtoReflect.Descriptor instead.
func (*QQLoginReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{15}
}

func (x *QQLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type QQLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
	UserId     string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId" form:"userId" query:"userId"`
}

func (x *QQLoginResp) Reset() {
	*x = QQLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QQLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQLoginResp) ProtoMessage() {}

func (x *QQLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQLoginResp.ProtoReflect.Descriptor instead.
func (*QQLoginResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{16}
}

func (x *QQLoginResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *QQLoginResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *QQLoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongToken string `protobuf:"bytes,1,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshTokenReq) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortToken string `protobuf:"bytes,1,opt,name=shortToken,proto3" json:"shortToken" form:"shortToken" query:"shortToken"`
	LongToken  string `protobuf:"bytes,2,opt,name=longToken,proto3" json:"longToken" form:"longToken" query:"longToken"`
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshTokenResp) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *RefreshTokenResp) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

type SendEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email   string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" form:"email" query:"email" vd:"email($)"`
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject" form:"subject" query:"subject"`
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{19}
}

func (x *SendEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SendEmailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendEmailResp) Reset() {
	*x = SendEmailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResp) ProtoMessage() {}

func (x *SendEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResp.ProtoReflect.Descriptor instead.
func (*SendEmailResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{20}
}

type GetCaptchaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCaptchaReq) Reset() {
	*x = GetCaptchaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReq) ProtoMessage() {}

func (x *GetCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReq.ProtoReflect.Descriptor instead.
func (*GetCaptchaReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{21}
}

type GetCaptchaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalImageBase64 string `protobuf:"bytes,1,opt,name=originalImageBase64,proto3" json:"originalImageBase64" form:"originalImageBase64" query:"originalImageBase64"`
	JigsawImageBase64   string `protobuf:"bytes,2,opt,name=jigsawImageBase64,proto3" json:"jigsawImageBase64" form:"jigsawImageBase64" query:"jigsawImageBase64"`
	Key                 string `protobuf:"bytes,3,opt,name=key,proto3" json:"key" form:"key" query:"key"`
}

func (x *GetCaptchaResp) Reset() {
	*x = GetCaptchaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResp) ProtoMessage() {}

func (x *GetCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResp.ProtoReflect.Descriptor instead.
func (*GetCaptchaResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetCaptchaResp) GetOriginalImageBase64() string {
	if x != nil {
		return x.OriginalImageBase64
	}
	return ""
}

func (x *GetCaptchaResp) GetJigsawImageBase64() string {
	if x != nil {
		return x.JigsawImageBase64
	}
	return ""
}

func (x *GetCaptchaResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetPasswordByEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" form:"email" query:"email" vd:"email($)"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" form:"password" query:"password"`
}

func (x *SetPasswordByEmailReq) Reset() {
	*x = SetPasswordByEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPasswordByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordByEmailReq) ProtoMessage() {}

func (x *SetPasswordByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordByEmailReq.ProtoReflect.Descriptor instead.
func (*SetPasswordByEmailReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{23}
}

func (x *SetPasswordByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetPasswordByEmailReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetPasswordByEmailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPasswordByEmailResp) Reset() {
	*x = SetPasswordByEmailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPasswordByEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordByEmailResp) ProtoMessage() {}

func (x *SetPasswordByEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordByEmailResp.ProtoReflect.Descriptor instead.
func (*SetPasswordByEmailResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{24}
}

type SetPasswordByPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldPassword string `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword" form:"oldPassword" query:"oldPassword"`
	Password    string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" form:"password" query:"password"`
}

func (x *SetPasswordByPasswordReq) Reset() {
	*x = SetPasswordByPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPasswordByPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordByPasswordReq) ProtoMessage() {}

func (x *SetPasswordByPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordByPasswordReq.ProtoReflect.Descriptor instead.
func (*SetPasswordByPasswordReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{25}
}

func (x *SetPasswordByPasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *SetPasswordByPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetPasswordByPasswordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPasswordByPasswordResp) Reset() {
	*x = SetPasswordByPasswordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPasswordByPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordByPasswordResp) ProtoMessage() {}

func (x *SetPasswordByPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordByPasswordResp.ProtoReflect.Descriptor instead.
func (*SetPasswordByPasswordResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{26}
}

type CheckEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" form:"email" query:"email" vd:"email($)"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code" form:"code" query:"code"`
}

func (x *CheckEmailReq) Reset() {
	*x = CheckEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailReq) ProtoMessage() {}

func (x *CheckEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailReq.ProtoReflect.Descriptor instead.
func (*CheckEmailReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{27}
}

func (x *CheckEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckEmailReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CheckEmailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok" form:"ok" query:"ok"`
}

func (x *CheckEmailResp) Reset() {
	*x = CheckEmailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailResp) ProtoMessage() {}

func (x *CheckEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailResp.ProtoReflect.Descriptor instead.
func (*CheckEmailResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{28}
}

func (x *CheckEmailResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AskUploadAvatarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name" query:"name"`
	AvatarSize int64  `protobuf:"varint,2,opt,name=avatarSize,proto3" json:"avatarSize" form:"avatarSize" query:"avatarSize"`
}

func (x *AskUploadAvatarReq) Reset() {
	*x = AskUploadAvatarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskUploadAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskUploadAvatarReq) ProtoMessage() {}

func (x *AskUploadAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskUploadAvatarReq.ProtoReflect.Descriptor instead.
func (*AskUploadAvatarReq) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{29}
}

func (x *AskUploadAvatarReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AskUploadAvatarReq) GetAvatarSize() int64 {
	if x != nil {
		return x.AvatarSize
	}
	return 0
}

type AskUploadAvatarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TmpSecretId  string `protobuf:"bytes,1,opt,name=tmpSecretId,proto3" json:"tmpSecretId" form:"tmpSecretId" query:"tmpSecretId"`
	TmpSecretKey string `protobuf:"bytes,2,opt,name=tmpSecretKey,proto3" json:"tmpSecretKey" form:"tmpSecretKey" query:"tmpSecretKey"`
	StartTime    int64  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime" form:"startTime" query:"startTime"`
	ExpiredTime  int64  `protobuf:"varint,4,opt,name=expiredTime,proto3" json:"expiredTime" form:"expiredTime" query:"expiredTime"`
	SessionToken string `protobuf:"bytes,5,opt,name=sessionToken,proto3" json:"sessionToken" form:"sessionToken" query:"sessionToken"`
}

func (x *AskUploadAvatarResp) Reset() {
	*x = AskUploadAvatarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloudmind_core_api_auth_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskUploadAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskUploadAvatarResp) ProtoMessage() {}

func (x *AskUploadAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloudmind_core_api_auth_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskUploadAvatarResp.ProtoReflect.Descriptor instead.
func (*AskUploadAvatarResp) Descriptor() ([]byte, []int) {
	return file_cloudmind_core_api_auth_proto_rawDescGZIP(), []int{30}
}

func (x *AskUploadAvatarResp) GetTmpSecretId() string {
	if x != nil {
		return x.TmpSecretId
	}
	return ""
}

func (x *AskUploadAvatarResp) GetTmpSecretKey() string {
	if x != nil {
		return x.TmpSecretKey
	}
	return ""
}

func (x *AskUploadAvatarResp) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AskUploadAvatarResp) GetExpiredTime() int64 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *AskUploadAvatarResp) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

var File_cloudmind_core_api_auth_proto protoreflect.FileDescriptor

var file_cloudmind_core_api_auth_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x1a, 0x1a, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x73,
	0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d,
	0x69, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1f, 0xda, 0xbb, 0x18, 0x1b, 0x6c, 0x65,
	0x6e, 0x28, 0x24, 0x29, 0x20, 0x3e, 0x3d, 0x20, 0x31, 0x20, 0x26, 0x26, 0x20, 0x6c, 0x65, 0x6e,
	0x28, 0x24, 0x29, 0x20, 0x3c, 0x3d, 0x20, 0x32, 0x30, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c,
	0xda, 0xbb, 0x18, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x28, 0x24, 0x29, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x73, 0x53, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x53, 0x75, 0x72, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xda, 0xbb, 0x18, 0x08, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x28, 0x24, 0x29, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x66, 0x0a, 0x0e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x47, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x0d, 0x47, 0x69, 0x74, 0x65, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x66, 0x0a, 0x0e, 0x47, 0x69, 0x74, 0x65, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x78, 0x0a,
	0x0c, 0x57, 0x78, 0x4d, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0xbd, 0x01, 0x0a, 0x11, 0x57, 0x65, 0x69, 0x78,
	0x69, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x63, 0x61, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x73, 0x63, 0x61, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x44, 0x0a, 0x0c, 0x77, 0x78, 0x4d, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d,
	0x69, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x78, 0x4d,
	0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x77, 0x78, 0x4d, 0x61, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3a, 0x0a, 0x12, 0x57, 0x65, 0x69, 0x78, 0x69,
	0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x47, 0x0a, 0x0f, 0x57, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x72, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32,
	0x0a, 0x10, 0x57, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x57, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x49, 0x73, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a, 0x0a, 0x51, 0x51, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x63, 0x0a, 0x0b, 0x51, 0x51, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a,
	0x0f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50,
	0x0a, 0x10, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0c, 0xda, 0xbb, 0x18, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x28, 0x24, 0x29, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71,
	0x22, 0x82, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x2c, 0x0a, 0x11, 0x6a, 0x69, 0x67, 0x73, 0x61, 0x77, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x6a, 0x69, 0x67, 0x73, 0x61, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x57, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x22,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xda,
	0xbb, 0x18, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x28, 0x24, 0x29, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x18,
	0x0a, 0x16, 0x53, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x58, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x47, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0c, 0xda, 0xbb, 0x18, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x28, 0x24, 0x29, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x48, 0x0a, 0x12, 0x41, 0x73,
	0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x13, 0x41, 0x73, 0x6b, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x74, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x74, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x74, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02, 0x12,
	0x1b, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x03, 0x42, 0x53, 0x5a, 0x51,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e,
	0x64, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloudmind_core_api_auth_proto_rawDescOnce sync.Once
	file_cloudmind_core_api_auth_proto_rawDescData = file_cloudmind_core_api_auth_proto_rawDesc
)

func file_cloudmind_core_api_auth_proto_rawDescGZIP() []byte {
	file_cloudmind_core_api_auth_proto_rawDescOnce.Do(func() {
		file_cloudmind_core_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloudmind_core_api_auth_proto_rawDescData)
	})
	return file_cloudmind_core_api_auth_proto_rawDescData
}

var file_cloudmind_core_api_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloudmind_core_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_cloudmind_core_api_auth_proto_goTypes = []interface{}{
	(UploadType)(0),                   // 0: cloudmind.core_api.UploadType
	(*RegisterReq)(nil),               // 1: cloudmind.core_api.RegisterReq
	(*RegisterResp)(nil),              // 2: cloudmind.core_api.RegisterResp
	(*EmailLoginReq)(nil),             // 3: cloudmind.core_api.EmailLoginReq
	(*EmailLoginResp)(nil),            // 4: cloudmind.core_api.EmailLoginResp
	(*GithubLoginReq)(nil),            // 5: cloudmind.core_api.GithubLoginReq
	(*GithubLoginResp)(nil),           // 6: cloudmind.core_api.GithubLoginResp
	(*GiteeLoginReq)(nil),             // 7: cloudmind.core_api.GiteeLoginReq
	(*GiteeLoginResp)(nil),            // 8: cloudmind.core_api.GiteeLoginResp
	(*WxMaUserInfo)(nil),              // 9: cloudmind.core_api.WxMaUserInfo
	(*WeixinCallBackReq)(nil),         // 10: cloudmind.core_api.WeixinCallBackReq
	(*WeixinCallBackResp)(nil),        // 11: cloudmind.core_api.WeixinCallBackResp
	(*WeixinLoginReq)(nil),            // 12: cloudmind.core_api.WeixinLoginReq
	(*WeixinLoginResp)(nil),           // 13: cloudmind.core_api.WeixinLoginResp
	(*WeixinIsLoginReq)(nil),          // 14: cloudmind.core_api.WeixinIsLoginReq
	(*WeixinIsLoginResp)(nil),         // 15: cloudmind.core_api.WeixinIsLoginResp
	(*QQLoginReq)(nil),                // 16: cloudmind.core_api.QQLoginReq
	(*QQLoginResp)(nil),               // 17: cloudmind.core_api.QQLoginResp
	(*RefreshTokenReq)(nil),           // 18: cloudmind.core_api.RefreshTokenReq
	(*RefreshTokenResp)(nil),          // 19: cloudmind.core_api.RefreshTokenResp
	(*SendEmailReq)(nil),              // 20: cloudmind.core_api.SendEmailReq
	(*SendEmailResp)(nil),             // 21: cloudmind.core_api.SendEmailResp
	(*GetCaptchaReq)(nil),             // 22: cloudmind.core_api.GetCaptchaReq
	(*GetCaptchaResp)(nil),            // 23: cloudmind.core_api.GetCaptchaResp
	(*SetPasswordByEmailReq)(nil),     // 24: cloudmind.core_api.SetPasswordByEmailReq
	(*SetPasswordByEmailResp)(nil),    // 25: cloudmind.core_api.SetPasswordByEmailResp
	(*SetPasswordByPasswordReq)(nil),  // 26: cloudmind.core_api.SetPasswordByPasswordReq
	(*SetPasswordByPasswordResp)(nil), // 27: cloudmind.core_api.SetPasswordByPasswordResp
	(*CheckEmailReq)(nil),             // 28: cloudmind.core_api.CheckEmailReq
	(*CheckEmailResp)(nil),            // 29: cloudmind.core_api.CheckEmailResp
	(*AskUploadAvatarReq)(nil),        // 30: cloudmind.core_api.AskUploadAvatarReq
	(*AskUploadAvatarResp)(nil),       // 31: cloudmind.core_api.AskUploadAvatarResp
	(*Keywords)(nil),                  // 32: cloudmind.core_api.Keywords
}
var file_cloudmind_core_api_auth_proto_depIdxs = []int32{
	32, // 0: cloudmind.core_api.RegisterResp.keywords:type_name -> cloudmind.core_api.Keywords
	9,  // 1: cloudmind.core_api.WeixinCallBackReq.wxMaUserInfo:type_name -> cloudmind.core_api.WxMaUserInfo
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}


func file_cloudmind_core_api_auth_proto_init() {
	if File_cloudmind_core_api_auth_proto != nil {
		return
	}
	file_cloudmind_core_api_content_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloudmind_core_api_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiteeLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiteeLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxMaUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinCallBackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinCallBackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinIsLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeixinIsLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QQLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QQLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPasswordByEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPasswordByEmailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPasswordByPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPasswordByPasswordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskUploadAvatarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloudmind_core_api_auth_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskUploadAvatarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloudmind_core_api_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloudmind_core_api_auth_proto_goTypes,
		DependencyIndexes: file_cloudmind_core_api_auth_proto_depIdxs,
		EnumInfos:         file_cloudmind_core_api_auth_proto_enumTypes,
		MessageInfos:      file_cloudmind_core_api_auth_proto_msgTypes,
	}.Build()
	File_cloudmind_core_api_auth_proto = out.File
	file_cloudmind_core_api_auth_proto_rawDesc = nil
	file_cloudmind_core_api_auth_proto_goTypes = nil
	file_cloudmind_core_api_auth_proto_depIdxs = nil
}
