// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/CloudStriver/cloudmind-core-api/biz/application/service"
	"github.com/CloudStriver/cloudmind-core-api/biz/infrastructure/config"
	"github.com/CloudStriver/cloudmind-core-api/biz/infrastructure/etcd"
	"github.com/CloudStriver/cloudmind-core-api/biz/infrastructure/rpc/cloudmind_sts"
	"github.com/CloudStriver/cloudmind-core-api/biz/infrastructure/rpc/cloudmind_user"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	resolver := etcd.NewEtcd(configConfig)
	client := cloudmind_user.NewCloudMindUser(resolver)
	cloudMindUser := &cloudmind_user.CloudMindUser{
		Client: client,
	}
	stsserviceClient := cloudmind_sts.NewCloudMindSts(resolver)
	cloudMindSts := &cloudmind_sts.CloudMindSts{
		Client: stsserviceClient,
	}
	contentService := &service.ContentService{
		Config:        configConfig,
		CloudMindUser: cloudMindUser,
		CloudMindSts:  cloudMindSts,
	}
	authService := &service.AuthService{
		Config:        configConfig,
		CloudMindUser: cloudMindUser,
		CloudMindSts:  cloudMindSts,
	}
	providerProvider := &Provider{
		Config:         configConfig,
		Etcd:           resolver,
		ContentService: contentService,
		AuthService:    authService,
	}
	return providerProvider, nil
}
