// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _giteeloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _githubloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordbyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordbypasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relation0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfromrelationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettorelationsMw() []app.HandlerFunc {
	// your code...
	return nil
}
