// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _giteeloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _githubloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordbyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordbypasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relation0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfromrelationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettorelationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addfiletopublicspaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfilecountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfileisexistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfilelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _movefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recoverrecyclebinfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savefiletoprivatespaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _folderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createfolderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfoldersizeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _labelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createlabelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletelabelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlabelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatelabelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsharecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesharecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfilebysharingcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _parsingsharecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesharecodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesharefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsharelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprivatefilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublicfilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecyclebinfilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createzoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletezoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatezoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprivatefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublicfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _askuploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _askuploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _askdownloadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completelyremovefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getotherpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getotherpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getownpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getownpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenotificationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnotificationcountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnotificationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenotificationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlatestrecommendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpopularrecommendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecommendbyitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecommendbyuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcommentsubjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentsubjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentsubjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setcommentattrsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setcommentstateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setcommentsubjectattrsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setcommentsubjectstateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecommentsubjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createobjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createobjectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteobjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlabelsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlabelsinbatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getobjectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateobjectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _readnotificationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsliderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesliderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getslidersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesliderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emptyrecyclebinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _zoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createzone0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletezone0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzone0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatezone0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzonesMw() []app.HandlerFunc {
	// your code...
	return nil
}
